import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Plugin to copy locale directory
const copyLocalePlugin = {
	name: 'copy-locale',
	setup(build) {
		build.onEnd(() => {
			const sourceDir = 'locale';
			const destDir = 'locale';

			// Create destination directory if it doesn't exist
			if (!fs.existsSync(destDir)) {
				fs.mkdirSync(destDir, { recursive: true });
			}

			// Copy all JSON files from locale directory
			if (fs.existsSync(sourceDir)) {
				const files = fs.readdirSync(sourceDir);
				files.forEach(file => {
					if (file.endsWith('.json')) {
						const sourcePath = path.join(sourceDir, file);
						const destPath = path.join(destDir, file);
						fs.copyFileSync(sourcePath, destPath);
						console.log(`Copied ${sourcePath} to ${destPath}`);
					}
				});
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [copyLocalePlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
